steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'your-dockerhub-username/mock-xtream-api:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mock-xtream-api'
      - '--image=your-dockerhub-username/mock-xtream-api:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=300'
      - '--concurrency=1000'

options:
  logging: CLOUD_LOGGING_ONLY